version: "3.9"

services:
  api:
    build: .
    container_name: finance-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npx nodemon src/index.js

  db:
    image: postgres:16
    container_name: finance-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: